# Generated by Django 4.0.6 on 2023-07-06 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCartView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.IntegerField()),
                ('product_id', models.IntegerField(default='')),
                ('user_id', models.IntegerField()),
                ('comment', models.CharField(max_length=1000)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('email_id', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default='')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('price', models.FloatField()),
                ('image', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoplane_app.rating')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('status', models.TextField(max_length=100)),
                ('sub_total', models.FloatField()),
                ('products', models.ManyToManyField(to='shoplane_app.product')),
            ],
        ),
    ]
